### ISSUE TITLE
Could you please reupload it please? it does not work

### ISSUE THREAD

**Issue by Mohamed-DL** [TheKiteFlier/L2_Siamese#2]
Hi, thank you for sharing your work. Could you please reupload it?

The code can't be uploaded to Colab, and it stops after a few minutes in Kaggle because it requires more memory. Please see the attached picture for the error. 

Thank you in advance. 

![L2-Siamese](https://github.com/ShowStopperTheSecond/L2_Siamese/assets/62818907/7c90e823-48de-4f19-8b8b-6104c85eae9f)

**Comment by ShowStopperTheSecond** [comment]
you need to clear the outputs before trying to upload in colab check out [this](https://stackoverflow.com/questions/28908319/how-to-clear-jupyter-notebooks-output-in-all-cells-from-the-linux-terminal). And about Kaggle; did you run the exact same notebook? It was working fine the last time I checked. The notebook in kaggle is the one after I allowed it to run and save the results
